# -*- coding: utf-8 -*-
"""FCC Group2-Cat2.ipynb

Automatically generated by Colab.

**GROUP TWO MEMBERS**
1.  EUGENE MWANGANGI- 224381
2.  KENNEDY ODUNGA - 73628
3.  HORACE OUMA OTIENO - 169702
4.  MULEI MUTUKU - 230016
5.  KIPROP AMOS - 225346

**Validation rules**
• Marks and attendance are numeric values from 0 to 100.  
• Student ID and programme are provided.  
• Project-submission status is a Boolean value.

**Coding Tasks**
* Store the records using an appropriate data structure. **(DONE)**
* Calculate final mark = 20% assignment + 20% CAT + 60% examination.
* Assign A (≥70), B (60–<70), C (50–<60), D (40–<50) or E (<40).
* Identify intervention cases: final mark below 50, attendance below 75%, or project not submitted.
* Calculate class average.**(DONE)**
* Identify highest and lowest final marks. **(DONE)**
* Count students in every grade. **(DONE)**
* Display a performance and intervention summary.

**Functions Assignment**
1. View valid students - Eugene
2. View invalid records
3. Analyse class performance - Mulei Mutuku **(DONE)**
4. View intervention list - Kiprop Amos
5. Search for a student
"""

# Storing the dataset using a list of dictionaries.
student_records = [
    {
        "student_id": "ST001",
        "programme": "MSc IT",
        "assignment_mark": 52,
        "cat_mark": 49,
        "exam_mark": 49,
        "attendance_pct": 64,
        "submitted_project": True
    },
    {
        "student_id": "ST002",
        "programme": "MSc AI",
        "assignment_mark": 59,
        "cat_mark": 58,
        "exam_mark": 60,
        "attendance_pct": 70,
        "submitted_project": True
    },
    {
        "student_id": "ST003",
        "programme": "MSc Data Science",
        "assignment_mark": 66,
        "cat_mark": 67,
        "exam_mark": 71,
        "attendance_pct": 76,
        "submitted_project": True
    },
    {
        "student_id": "ST004",
        "programme": "MSc IT",
        "assignment_mark": 73,
        "cat_mark": 76,
        "exam_mark": 82,
        "attendance_pct": 82,
        "submitted_project": True
    },
    {
        "student_id": "ST005",
        "programme": "MSc AI",
        "assignment_mark": 80,
        "cat_mark": None,
        "exam_mark": 93,
        "attendance_pct": 88,
        "submitted_project": False
    },
    {
        "student_id": "ST006",
        "programme": "MSc Data Science",
        "assignment_mark": 87,
        "cat_mark": 94,
        "exam_mark": 43,
        "attendance_pct": 94,
        "submitted_project": True
    },
    {
        "student_id": "ST007",
        "programme": "MSc IT",
        "assignment_mark": 94,
        "cat_mark": 47,
        "exam_mark": 54,
        "attendance_pct": 100,
        "submitted_project": True
    },
    {
        "student_id": "ST008",
        "programme": "MSc AI",
        "assignment_mark": 50,
        "cat_mark": 56,
        "exam_mark": 65,
        "attendance_pct": 63,
        "submitted_project": True
    },
    {
        "student_id": "ST009",
        "programme": "MSc Data Science",
        "assignment_mark": 57,
        "cat_mark": 65,
        "exam_mark": 76,
        "attendance_pct": 69,
        "submitted_project": True
    },
    {
        "student_id": "ST010",
        "programme": "MSc IT",
        "assignment_mark": 64,
        "cat_mark": 74,
        "exam_mark": 87,
        "attendance_pct": 75,
        "submitted_project": False
    },
    {
        "student_id": "ST011",
        "programme": "MSc AI",
        "assignment_mark": 71,
        "cat_mark": 83,
        "exam_mark": 98,
        "attendance_pct": 81,
        "submitted_project": True
    },
    {
        "student_id": "ST012",
        "programme": "MSc Data Science",
        "assignment_mark": 78,
        "cat_mark": 92,
        "exam_mark": 108,
        "attendance_pct": 87,
        "submitted_project": True
    },
    {
        "student_id": "ST013",
        "programme": "MSc IT",
        "assignment_mark": 85,
        "cat_mark": 45,
        "exam_mark": 59,
        "attendance_pct": 93,
        "submitted_project": True
    },
    {
        "student_id": "ST014",
        "programme": "MSc AI",
        "assignment_mark": 92,
        "cat_mark": 54,
        "exam_mark": 70,
        "attendance_pct": 99,
        "submitted_project": True
    },
    {
        "student_id": "ST015",
        "programme": "MSc Data Science",
        "assignment_mark": 48,
        "cat_mark": 63,
        "exam_mark": 81,
        "attendance_pct": 62,
        "submitted_project": False
    },
    {
        "student_id": "ST016",
        "programme": "MSc IT",
        "assignment_mark": 55,
        "cat_mark": 72,
        "exam_mark": 92,
        "attendance_pct": 68,
        "submitted_project": True
    },
    {
        "student_id": "ST017",
        "programme": "msc data science",
        "assignment_mark": 62,
        "cat_mark": 81,
        "exam_mark": 42,
        "attendance_pct": 74,
        "submitted_project": True
    },
    {
        "student_id": "ST018",
        "programme": "MSc Data Science",
        "assignment_mark": 69,
        "cat_mark": 90,
        "exam_mark": 53,
        "attendance_pct": 80,
        "submitted_project": True
    },
    {
        "student_id": "ST019",
        "programme": "MSc IT",
        "assignment_mark": 76,
        "cat_mark": 43,
        "exam_mark": 64,
        "attendance_pct": 86,
        "submitted_project": True
    },
    {
        "student_id": "ST020",
        "programme": "MSc AI",
        "assignment_mark": 83,
        "cat_mark": 52,
        "exam_mark": 75,
        "attendance_pct": 92,
        "submitted_project": False
    }
]


"""**1: View valid and Invalid Stident Records** 
    Validation rules
    Marks and attendance are numeric values from 0 to 100.
    Student ID and programme are provided.
    Project-submission status is a Boolean value
"""


def validate_records(records):
  """Validates records and stores them in global lists."""
  valid_students = []
  invalid_records = []

  for record in records:
      is_valid = True
      reasons = []

      # 1. Student ID and programme are provided
      record['student_id']
      if not record.get("student_id"):
          is_valid = False
          reasons.append("Missing Student ID")
      if not record.get("programme"):
          is_valid = False
          reasons.append("Missing Programme")

      # 2. Project-submission status is a Boolean value
      if not isinstance(record.get("submitted_project"), bool):
          is_valid = False
          reasons.append("Project status not boolean")

      # 3. Marks and attendance are numeric values from 0 to 100
      numeric_fields = ["assignment_mark", "cat_mark", "exam_mark", "attendance_pct"]
      for field in numeric_fields:
          val = record.get(field)
          if not isinstance(val, (int, float)):
              is_valid = False
              reasons.append(f"{field} is not numeric")
          elif not (0 <= val <= 100):
              is_valid = False
              reasons.append(f"{field} out of range (0-100)")

      if is_valid:
          valid_students.append(record)
      else:
          record_copy = record.copy()
          record_copy['invalid_reason'] = ", ".join(reasons)
          invalid_records.append(record_copy)

  return valid_students, invalid_records

# Display valid students function
def display_valid_students(valid_students):
  """Displays the list of valid students."""
  print("--- Valid Student Records ---")

  if not valid_students:
      print("No valid records found. Run validate_records first.")
  else: 
      for record in valid_students:
          print("\n----------Student Details-----------")
          for key,value in record.items():
            # capitalize the keya values i.e "student_id" to "Student Id"
            key = " ".join([ i.title() for i in key.split("_")]) 
            print(f"{key}: {value}")
  print("-----------------------------\n")

# display invalid students function
def display_invalid_records(invalid_records):
  """Displays the list of invalid records with reasons."""
  print("--- Invalid Student Records ---")
  if not invalid_records:
      print("No invalid records found. Run validate_records first.")
  else:
      for rec in invalid_records:
          s_id = rec.get('student_id', 'N/A')
          reason = rec.get('invalid_reason', 'Unknown error')
          print(f"ID: {s_id} | Reason(s): {reason}")       
  print("-------------------------------\n")



"""**3: Analyze Class Perfomance**
1. Calculate class average
2. Identify highest and lowest final marks.
3. Count students in every grade.
4. Display a performance and intervention summary.
"""


# function for calculating class avergae
def calculate_class_statistics(valid_students):
  # Creating empty data structures for storung results
  final_marks = [ mark['final_mark'] for mark in grade_final_mark(valid_students)]
  class_average = None
  result = dict()

  #list of only the correct marks without blanks
  class_average = sum(final_marks) / len(final_marks)
  highest_final_mark = max(final_marks)
  lowest_final_mark = min(final_marks)

  result['class_average'] = round(class_average,2)
  result['student_marks'] = final_marks
  result['highest_final_mark'] = highest_final_mark
  result['lowest_final_mark'] = lowest_final_mark
  result['students'] = len(final_marks)

  # returning a dictionary of output
  return result

# function to claculate final marks from assignment , cat and exam marks
def calculate_final_mark(valid_students):
  final_marks = None # Creating empty variable to store final mark
  new_student_records = list() # Creating empty list to new student details
  # looping through student records calculating final marks
  for record in valid_students:
    final_mark = (record['assignment_mark']*0.2) + (record['cat_mark']*0.2) + (record['exam_mark']*0.6)
    final_mark = round(final_mark,2)
    record['final_mark'] = final_mark
    new_student_records.append(record)
  # returning the student records with added final marks
  return new_student_records

# function to grade a student marks
def grade_final_mark(valid_students):
  grade = None # Creating empty variable to store grades
  new_student_records = list() # Creating empty list to new student details
  valid_students = calculate_final_mark(valid_students)
   # looping through student records calculating grades
  for record in valid_students:
    final_mark = record['final_mark']
    if final_mark >=70: grade = "A"
    elif final_mark >=60: grade = "B"
    elif final_mark >=50: grade = "C"
    elif final_mark >=40: grade = "D"
    else: grade = "E"
    record['grade'] = grade
    new_student_records.append(record)
  # returning the student records with added grades
  return new_student_records

# function to count grades in class final marks
def count_students_in_every_grade(valid_students):
  grade_counts = {'A': 0, 'B': 0, 'C': 0, 'D': 0, 'E': 0, 'F': 0}
  valid_students = grade_final_mark(valid_students)
  for record in valid_students:
    grade = record['grade']
    grade_counts[grade] += 1

  return grade_counts

# function to display class perfomance
def display_perfomance(valid_students):
  stats = calculate_class_statistics(valid_students)
  grade_counts = count_students_in_every_grade(valid_students)
  print("\n--------------Class Perfomance Summary---------------")
  print(f"Class Average: {stats['class_average']} ")
  print(f"Highest Mark: {stats['highest_final_mark']}")
  print(f"Lowest Mark: {stats['lowest_final_mark']}")
  print(f"Total Students: {stats['students']}")
  print(f"Grades Summary: {grade_counts}")



"""**4.0 View Intervention List**

Intervention cases:

1. final mark below 50
2. attendance below 75%
3. project not submitted.
"""

# Intervention List
def view_intervention_list(valid_students):
    """Identify and display students requiring intervention."""
    print("\n--- Intervention List ---")

     # Initialize flag to track if any student needs intervention
    intervention_found = False

    # Iterate through each student record to evaluate intervention criteria
    for student in valid_students:
        # List to hold the explanation why the the student needss intervention
        reasons = []

        # Check each intervention condition separately
        # Condition 1: final mark below 50
        if student["final_mark"] < 50:
            reasons.append("Final mark below 50")

        # Condition 2: attendance below 75%
        if student["attendance_pct"] < 75:
            reasons.append("Attendance below 75%")

        # Condition 3: project not submitted
        if student["submitted_project"] is False:
            reasons.append("Project not submitted")

        # Display the student if at least one reason exists
        if reasons: # Check if list is empty
            intervention_found = True

            # Print details of flagged students
            print(f"\nStudent ID: {student['student_id']}")
            print(f"Submitted Project: {student['submitted_project']}")
            print(f"Final mark: {student['final_mark']:.2f}")
            print(f"Attendance: {student['attendance_pct']}%")
            print("Intervention reasons:")

            for reason in reasons:
                print(f"- {reason}")

    # Fallback if no students were flagged
    if intervention_found == False:
        print("No students require intervention.")
        
"""**5.0 Search For Student**"""

def search_for_student(student_id: None):
  # capture student ID no
  if student_id is None:
    student_id = input("Enter student ID No: ").strip()
  elif student_id == "#":
    return None

  # validating entered id
  # and recapture wrong entered ID Nos 
  while not student_id.isdigit():
    student_id = input("Invalid ID, number only required[0-9]: ").strip()

  # Formarting student id
  student_id = "ST"+student_id.zfill(3)

  # loop through student records
  for record in student_records:
    if record['student_id'] == student_id:
      print("\n----------Student Details-----------")
      for key,value in record.items():
        key = " ".join([ i.title() for i in key.split("_")])
        print(f"{key}: {value}")
      return None
    else: continue

  print("Student not found")
  return None



"""**MENU**"""

def main_menu():
  print('\nStudent Perfomance Worksheet Software')
  print('FCC Group 2')
  print('-------------Menu----------------')
  print('1: View Valid Students')
  print('2: View Invalid Records')
  print('3: Analyze Class Perfomance')
  print('4: View Intervention List')
  print('5: Search For a Student')
  print('6.Exit')

while True:
  main_menu()
  selection = int(input('\nPlease make a selection from the menu: '))
  valid_students, invalid_records = validate_records(student_records)
  grade_final_mark(valid_students) # this adds the final marks and grades to each student
  if selection == 1:
    display_valid_students(valid_students)

  elif selection == 2:
    display_invalid_records(invalid_records)

  elif selection == 3: 
    display_perfomance(valid_students)

  elif selection == 4:
    view_intervention_list(valid_students)
      
  elif selection == 5:
      while True :
        selection_ = input("Enter student ID No: ").strip()
        search_for_student(selection_)
        if selection == "#":
          print("Back to Main Menu")
          break
        print('\nEnter #: To Exit To Main Menu')

  elif selection == 6:
    print("Program closed.")
    break
  else:
    print("Invalid selection.")

